// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comcn.proto

package comcn

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InternalMessage struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalMessage) Reset()         { *m = InternalMessage{} }
func (m *InternalMessage) String() string { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()    {}
func (*InternalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c87860613cddd7c, []int{0}
}

func (m *InternalMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalMessage.Unmarshal(m, b)
}
func (m *InternalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalMessage.Marshal(b, m, deterministic)
}
func (m *InternalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalMessage.Merge(m, src)
}
func (m *InternalMessage) XXX_Size() int {
	return xxx_messageInfo_InternalMessage.Size(m)
}
func (m *InternalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InternalMessage proto.InternalMessageInfo

func (m *InternalMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Input struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	NodePassword         string   `protobuf:"bytes,3,opt,name=NodePassword,proto3" json:"NodePassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c87860613cddd7c, []int{1}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Input) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Input) GetNodePassword() string {
	if m != nil {
		return m.NodePassword
	}
	return ""
}

type Output struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c87860613cddd7c, []int{2}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Output) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Output) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InternalMessage)(nil), "InternalMessage")
	proto.RegisterType((*Input)(nil), "Input")
	proto.RegisterType((*Output)(nil), "Output")
}

func init() {
	proto.RegisterFile("comcn.proto", fileDescriptor_5c87860613cddd7c)
}

var fileDescriptor_5c87860613cddd7c = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xa5, 0xa6, 0xdd, 0xd6, 0x67, 0xc4, 0x32, 0x08, 0x26, 0x9e, 0x42, 0x2e, 0x7a, 0xca, 0xa1,
	0x7e, 0x42, 0x2b, 0x52, 0xc5, 0x2a, 0x5b, 0xf4, 0xbe, 0x76, 0x07, 0x2f, 0x31, 0x1b, 0x92, 0x0d,
	0xea, 0xdf, 0x4b, 0x26, 0x29, 0x45, 0x2d, 0xbd, 0xbd, 0x37, 0x6f, 0xe6, 0xcd, 0xec, 0x5b, 0x9c,
	0x6c, 0xdc, 0xc7, 0xa6, 0xc8, 0xca, 0xca, 0x79, 0x97, 0x5e, 0xe1, 0x6c, 0x59, 0x78, 0xae, 0x0a,
	0x93, 0x3f, 0x72, 0x5d, 0x9b, 0x77, 0xa6, 0x73, 0x8c, 0x5e, 0x4d, 0xde, 0x70, 0x34, 0x48, 0x06,
	0xd7, 0xa1, 0xee, 0x48, 0xba, 0xc6, 0x68, 0x59, 0x94, 0x8d, 0xa7, 0x29, 0x82, 0x07, 0xfe, 0x16,
	0xf1, 0x58, 0xb7, 0x70, 0x37, 0x70, 0x24, 0xb5, 0x8e, 0x50, 0x8a, 0x70, 0xe5, 0x2c, 0x3f, 0x9b,
	0xba, 0xfe, 0x74, 0x95, 0x8d, 0x02, 0x11, 0x7f, 0xd5, 0xd2, 0x7b, 0xa8, 0xa7, 0xc6, 0xb7, 0xae,
	0x84, 0xe1, 0xdc, 0xd9, 0x6e, 0xe7, 0xa9, 0x16, 0x4c, 0x11, 0xc6, 0xfd, 0x4d, 0xbd, 0xf3, 0x96,
	0xb6, 0xdd, 0x0b, 0xe3, 0x8d, 0x78, 0x86, 0x5a, 0xf0, 0xcc, 0x63, 0x72, 0xfb, 0xd5, 0xbd, 0x84,
	0x62, 0xa8, 0x79, 0xc5, 0xc6, 0x33, 0xa9, 0x4c, 0xae, 0xbe, 0x1c, 0x67, 0xfd, 0xa2, 0x0b, 0x0c,
	0x35, 0x1b, 0xfb, 0x5f, 0x88, 0xa1, 0x5e, 0x4a, 0xbb, 0x77, 0x26, 0x86, 0x5a, 0x70, 0xce, 0x7b,
	0xa4, 0xd9, 0x0a, 0x93, 0x6d, 0x7e, 0x94, 0x20, 0xb8, 0x63, 0x4f, 0xd3, 0xec, 0x4f, 0xa2, 0x3b,
	0xa3, 0x04, 0xc1, 0xfa, 0x60, 0xc7, 0x9b, 0x92, 0x6f, 0xb9, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xb1, 0xad, 0x70, 0x82, 0xa5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExternalClient is the client API for External service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExternalClient interface {
	Create(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	Read(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	Update(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	Delete(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
}

type externalClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalClient(cc grpc.ClientConnInterface) ExternalClient {
	return &externalClient{cc}
}

func (c *externalClient) Create(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/External/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) Read(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/External/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) Update(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/External/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) Delete(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/External/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServer is the server API for External service.
type ExternalServer interface {
	Create(context.Context, *Input) (*Output, error)
	Read(context.Context, *Input) (*Output, error)
	Update(context.Context, *Input) (*Output, error)
	Delete(context.Context, *Input) (*Output, error)
}

// UnimplementedExternalServer can be embedded to have forward compatible implementations.
type UnimplementedExternalServer struct {
}

func (*UnimplementedExternalServer) Create(ctx context.Context, req *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedExternalServer) Read(ctx context.Context, req *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedExternalServer) Update(ctx context.Context, req *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedExternalServer) Delete(ctx context.Context, req *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterExternalServer(s *grpc.Server, srv ExternalServer) {
	s.RegisterService(&_External_serviceDesc, srv)
}

func _External_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Create(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Read(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Update(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Delete(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _External_serviceDesc = grpc.ServiceDesc{
	ServiceName: "External",
	HandlerType: (*ExternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _External_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _External_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _External_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _External_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comcn.proto",
}

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalClient interface {
	Get(ctx context.Context, in *InternalMessage, opts ...grpc.CallOption) (*Output, error)
	Set(ctx context.Context, in *InternalMessage, opts ...grpc.CallOption) (*Output, error)
}

type internalClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalClient(cc grpc.ClientConnInterface) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) Get(ctx context.Context, in *InternalMessage, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/Internal/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) Set(ctx context.Context, in *InternalMessage, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/Internal/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServer is the server API for Internal service.
type InternalServer interface {
	Get(context.Context, *InternalMessage) (*Output, error)
	Set(context.Context, *InternalMessage) (*Output, error)
}

// UnimplementedInternalServer can be embedded to have forward compatible implementations.
type UnimplementedInternalServer struct {
}

func (*UnimplementedInternalServer) Get(ctx context.Context, req *InternalMessage) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedInternalServer) Set(ctx context.Context, req *InternalMessage) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterInternalServer(s *grpc.Server, srv InternalServer) {
	s.RegisterService(&_Internal_serviceDesc, srv)
}

func _Internal_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Internal/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Get(ctx, req.(*InternalMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Internal/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Set(ctx, req.(*InternalMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Internal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Internal_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Internal_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comcn.proto",
}
