// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocom.proto

package protocom

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=StatusCode,json=statusCode,proto3" json:"StatusCode,omitempty"`
	CustomCode           string   `protobuf:"bytes,2,opt,name=CustomCode,json=customCode,proto3" json:"CustomCode,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetCustomCode() string {
	if m != nil {
		return m.CustomCode
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExternalGetRequestElement struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	ControllerID         string   `protobuf:"bytes,2,opt,name=ControllerID,json=controllerID,proto3" json:"ControllerID,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalGetRequestElement) Reset()         { *m = ExternalGetRequestElement{} }
func (m *ExternalGetRequestElement) String() string { return proto.CompactTextString(m) }
func (*ExternalGetRequestElement) ProtoMessage()    {}
func (*ExternalGetRequestElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{1}
}

func (m *ExternalGetRequestElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalGetRequestElement.Unmarshal(m, b)
}
func (m *ExternalGetRequestElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalGetRequestElement.Marshal(b, m, deterministic)
}
func (m *ExternalGetRequestElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalGetRequestElement.Merge(m, src)
}
func (m *ExternalGetRequestElement) XXX_Size() int {
	return xxx_messageInfo_ExternalGetRequestElement.Size(m)
}
func (m *ExternalGetRequestElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalGetRequestElement.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalGetRequestElement proto.InternalMessageInfo

func (m *ExternalGetRequestElement) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ExternalGetRequestElement) GetControllerID() string {
	if m != nil {
		return m.ControllerID
	}
	return ""
}

func (m *ExternalGetRequestElement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ExternalGetRequest struct {
	Data                 []*ExternalGetRequestElement `protobuf:"bytes,1,rep,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ExternalGetRequest) Reset()         { *m = ExternalGetRequest{} }
func (m *ExternalGetRequest) String() string { return proto.CompactTextString(m) }
func (*ExternalGetRequest) ProtoMessage()    {}
func (*ExternalGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{2}
}

func (m *ExternalGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalGetRequest.Unmarshal(m, b)
}
func (m *ExternalGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalGetRequest.Marshal(b, m, deterministic)
}
func (m *ExternalGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalGetRequest.Merge(m, src)
}
func (m *ExternalGetRequest) XXX_Size() int {
	return xxx_messageInfo_ExternalGetRequest.Size(m)
}
func (m *ExternalGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalGetRequest proto.InternalMessageInfo

func (m *ExternalGetRequest) GetData() []*ExternalGetRequestElement {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExternalSetRequestElement struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	ControllerID         string   `protobuf:"bytes,2,opt,name=ControllerID,json=controllerID,proto3" json:"ControllerID,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalSetRequestElement) Reset()         { *m = ExternalSetRequestElement{} }
func (m *ExternalSetRequestElement) String() string { return proto.CompactTextString(m) }
func (*ExternalSetRequestElement) ProtoMessage()    {}
func (*ExternalSetRequestElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{3}
}

func (m *ExternalSetRequestElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalSetRequestElement.Unmarshal(m, b)
}
func (m *ExternalSetRequestElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalSetRequestElement.Marshal(b, m, deterministic)
}
func (m *ExternalSetRequestElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalSetRequestElement.Merge(m, src)
}
func (m *ExternalSetRequestElement) XXX_Size() int {
	return xxx_messageInfo_ExternalSetRequestElement.Size(m)
}
func (m *ExternalSetRequestElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalSetRequestElement.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalSetRequestElement proto.InternalMessageInfo

func (m *ExternalSetRequestElement) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ExternalSetRequestElement) GetControllerID() string {
	if m != nil {
		return m.ControllerID
	}
	return ""
}

func (m *ExternalSetRequestElement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ExternalSetRequestElement) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ExternalSetRequest struct {
	Data                 []*ExternalSetRequestElement `protobuf:"bytes,1,rep,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ExternalSetRequest) Reset()         { *m = ExternalSetRequest{} }
func (m *ExternalSetRequest) String() string { return proto.CompactTextString(m) }
func (*ExternalSetRequest) ProtoMessage()    {}
func (*ExternalSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{4}
}

func (m *ExternalSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalSetRequest.Unmarshal(m, b)
}
func (m *ExternalSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalSetRequest.Marshal(b, m, deterministic)
}
func (m *ExternalSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalSetRequest.Merge(m, src)
}
func (m *ExternalSetRequest) XXX_Size() int {
	return xxx_messageInfo_ExternalSetRequest.Size(m)
}
func (m *ExternalSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalSetRequest proto.InternalMessageInfo

func (m *ExternalSetRequest) GetData() []*ExternalSetRequestElement {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ExternalGetRequestElement)(nil), "ExternalGetRequestElement")
	proto.RegisterType((*ExternalGetRequest)(nil), "ExternalGetRequest")
	proto.RegisterType((*ExternalSetRequestElement)(nil), "ExternalSetRequestElement")
	proto.RegisterType((*ExternalSetRequest)(nil), "ExternalSetRequest")
}

func init() {
	proto.RegisterFile("protocom.proto", fileDescriptor_b3d33cdd7d7944cd)
}

var fileDescriptor_b3d33cdd7d7944cd = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xb7, 0xb5, 0xcd, 0x58, 0x8a, 0x8c, 0x1e, 0x62, 0x0f, 0x12, 0x02, 0x85, 0x9c,
	0x72, 0xa8, 0x3f, 0xa1, 0x29, 0xa5, 0x88, 0x97, 0x5d, 0x10, 0xaf, 0x6b, 0x3a, 0x88, 0x98, 0x64,
	0x6b, 0x76, 0xa2, 0xed, 0xbf, 0x97, 0xae, 0x31, 0x56, 0x8c, 0x78, 0xf2, 0xb6, 0xf3, 0xde, 0x83,
	0xf7, 0xed, 0x30, 0x30, 0xd9, 0x56, 0x86, 0x4d, 0x66, 0x8a, 0xc4, 0x3d, 0xa2, 0x1d, 0x8c, 0x24,
	0xd9, 0xad, 0x29, 0x2d, 0xe1, 0x15, 0x80, 0x62, 0xcd, 0xb5, 0x5d, 0x98, 0x0d, 0x05, 0x5e, 0xe8,
	0xc5, 0x42, 0x82, 0x6d, 0x95, 0x83, 0xbf, 0xa8, 0x2d, 0x9b, 0xc2, 0xf9, 0xbd, 0xd0, 0x8b, 0x7d,
	0x09, 0x59, 0xab, 0x60, 0x00, 0xc3, 0x5b, 0xb2, 0x56, 0x3f, 0x52, 0x20, 0x9c, 0x39, 0x2c, 0x3e,
	0x46, 0x44, 0xe8, 0xa7, 0x9a, 0x75, 0xd0, 0x0f, 0xbd, 0x78, 0x2c, 0xfb, 0x1b, 0xcd, 0x3a, 0xd2,
	0x70, 0xb9, 0xdc, 0x31, 0x55, 0xa5, 0xce, 0x57, 0xc4, 0x92, 0x5e, 0x6a, 0xb2, 0xbc, 0xcc, 0xa9,
	0xa0, 0x92, 0x71, 0x02, 0xbd, 0x75, 0xea, 0x10, 0x7c, 0xd9, 0x7b, 0x4a, 0x31, 0x82, 0xf1, 0xc2,
	0x94, 0x5c, 0x99, 0x3c, 0xa7, 0x6a, 0x9d, 0x36, 0xe5, 0xe3, 0xec, 0x48, 0xc3, 0x33, 0x10, 0x37,
	0xb4, 0x6f, 0xaa, 0xc5, 0x33, 0xed, 0xa3, 0x14, 0xf0, 0x67, 0x05, 0x26, 0x0d, 0x8c, 0x17, 0x8a,
	0xf8, 0x74, 0x3e, 0x4d, 0x7e, 0xa5, 0x68, 0x40, 0xdf, 0xbe, 0x40, 0xd5, 0xff, 0x80, 0xe2, 0x05,
	0x0c, 0xee, 0x74, 0x5e, 0x93, 0x5b, 0x90, 0x2f, 0x07, 0xaf, 0x87, 0xe1, 0x18, 0x5f, 0xfd, 0x8d,
	0xaf, 0xba, 0xf1, 0xe7, 0xf7, 0x30, 0xfa, 0x8c, 0xe0, 0x0c, 0xc4, 0x8a, 0x18, 0xcf, 0x3b, 0xfe,
	0x3c, 0xf5, 0x93, 0xf6, 0x10, 0x66, 0x20, 0xd4, 0xb7, 0x98, 0xea, 0x8a, 0x3d, 0x9c, 0xb8, 0x13,
	0xba, 0x7e, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xf1, 0x08, 0x70, 0x54, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExternalClient is the client API for External service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExternalClient interface {
	Get(ctx context.Context, in *ExternalGetRequest, opts ...grpc.CallOption) (*Response, error)
	Set(ctx context.Context, in *ExternalSetRequest, opts ...grpc.CallOption) (*Response, error)
}

type externalClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalClient(cc grpc.ClientConnInterface) ExternalClient {
	return &externalClient{cc}
}

func (c *externalClient) Get(ctx context.Context, in *ExternalGetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/External/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) Set(ctx context.Context, in *ExternalSetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/External/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServer is the server API for External service.
type ExternalServer interface {
	Get(context.Context, *ExternalGetRequest) (*Response, error)
	Set(context.Context, *ExternalSetRequest) (*Response, error)
}

// UnimplementedExternalServer can be embedded to have forward compatible implementations.
type UnimplementedExternalServer struct {
}

func (*UnimplementedExternalServer) Get(ctx context.Context, req *ExternalGetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedExternalServer) Set(ctx context.Context, req *ExternalSetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterExternalServer(s *grpc.Server, srv ExternalServer) {
	s.RegisterService(&_External_serviceDesc, srv)
}

func _External_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Get(ctx, req.(*ExternalGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Set(ctx, req.(*ExternalSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _External_serviceDesc = grpc.ServiceDesc{
	ServiceName: "External",
	HandlerType: (*ExternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _External_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _External_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocom.proto",
}
