// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocom.proto

package protocom

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=StatusCode,json=statusCode,proto3" json:"StatusCode,omitempty"`
	CustomCode           string   `protobuf:"bytes,2,opt,name=CustomCode,json=customCode,proto3" json:"CustomCode,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetCustomCode() string {
	if m != nil {
		return m.CustomCode
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExternalGetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalGetRequest) Reset()         { *m = ExternalGetRequest{} }
func (m *ExternalGetRequest) String() string { return proto.CompactTextString(m) }
func (*ExternalGetRequest) ProtoMessage()    {}
func (*ExternalGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{1}
}

func (m *ExternalGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalGetRequest.Unmarshal(m, b)
}
func (m *ExternalGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalGetRequest.Marshal(b, m, deterministic)
}
func (m *ExternalGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalGetRequest.Merge(m, src)
}
func (m *ExternalGetRequest) XXX_Size() int {
	return xxx_messageInfo_ExternalGetRequest.Size(m)
}
func (m *ExternalGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalGetRequest proto.InternalMessageInfo

func (m *ExternalGetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ExternalSetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalSetRequest) Reset()         { *m = ExternalSetRequest{} }
func (m *ExternalSetRequest) String() string { return proto.CompactTextString(m) }
func (*ExternalSetRequest) ProtoMessage()    {}
func (*ExternalSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{2}
}

func (m *ExternalSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalSetRequest.Unmarshal(m, b)
}
func (m *ExternalSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalSetRequest.Marshal(b, m, deterministic)
}
func (m *ExternalSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalSetRequest.Merge(m, src)
}
func (m *ExternalSetRequest) XXX_Size() int {
	return xxx_messageInfo_ExternalSetRequest.Size(m)
}
func (m *ExternalSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalSetRequest proto.InternalMessageInfo

func (m *ExternalSetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ExternalSetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InternalGetRequest struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=NodeID,json=nodeID,proto3" json:"NodeID,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalGetRequest) Reset()         { *m = InternalGetRequest{} }
func (m *InternalGetRequest) String() string { return proto.CompactTextString(m) }
func (*InternalGetRequest) ProtoMessage()    {}
func (*InternalGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{3}
}

func (m *InternalGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalGetRequest.Unmarshal(m, b)
}
func (m *InternalGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalGetRequest.Marshal(b, m, deterministic)
}
func (m *InternalGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalGetRequest.Merge(m, src)
}
func (m *InternalGetRequest) XXX_Size() int {
	return xxx_messageInfo_InternalGetRequest.Size(m)
}
func (m *InternalGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalGetRequest proto.InternalMessageInfo

func (m *InternalGetRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *InternalGetRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InternalGetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LeaderHeartbeatRequest struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=NodeID,json=nodeID,proto3" json:"NodeID,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderHeartbeatRequest) Reset()         { *m = LeaderHeartbeatRequest{} }
func (m *LeaderHeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*LeaderHeartbeatRequest) ProtoMessage()    {}
func (*LeaderHeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{4}
}

func (m *LeaderHeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderHeartbeatRequest.Unmarshal(m, b)
}
func (m *LeaderHeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderHeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *LeaderHeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderHeartbeatRequest.Merge(m, src)
}
func (m *LeaderHeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_LeaderHeartbeatRequest.Size(m)
}
func (m *LeaderHeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderHeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderHeartbeatRequest proto.InternalMessageInfo

func (m *LeaderHeartbeatRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *LeaderHeartbeatRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LeaderHeartbeatRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AskVoteRequest struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=NodeID,json=nodeID,proto3" json:"NodeID,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskVoteRequest) Reset()         { *m = AskVoteRequest{} }
func (m *AskVoteRequest) String() string { return proto.CompactTextString(m) }
func (*AskVoteRequest) ProtoMessage()    {}
func (*AskVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3d33cdd7d7944cd, []int{5}
}

func (m *AskVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskVoteRequest.Unmarshal(m, b)
}
func (m *AskVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskVoteRequest.Marshal(b, m, deterministic)
}
func (m *AskVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskVoteRequest.Merge(m, src)
}
func (m *AskVoteRequest) XXX_Size() int {
	return xxx_messageInfo_AskVoteRequest.Size(m)
}
func (m *AskVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskVoteRequest proto.InternalMessageInfo

func (m *AskVoteRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *AskVoteRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ExternalGetRequest)(nil), "ExternalGetRequest")
	proto.RegisterType((*ExternalSetRequest)(nil), "ExternalSetRequest")
	proto.RegisterType((*InternalGetRequest)(nil), "InternalGetRequest")
	proto.RegisterType((*LeaderHeartbeatRequest)(nil), "LeaderHeartbeatRequest")
	proto.RegisterType((*AskVoteRequest)(nil), "AskVoteRequest")
}

func init() {
	proto.RegisterFile("protocom.proto", fileDescriptor_b3d33cdd7d7944cd)
}

var fileDescriptor_b3d33cdd7d7944cd = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x53, 0x5b, 0xfe, 0x8d, 0x06, 0xcd, 0x60, 0xb0, 0xf1, 0x60, 0x48, 0x13, 0x0c, 0x17,
	0x7b, 0xc0, 0x93, 0x09, 0x17, 0x03, 0x06, 0x89, 0x7f, 0x0e, 0x5b, 0x43, 0xbc, 0x2e, 0x74, 0xe2,
	0x01, 0xda, 0xc5, 0xee, 0xd4, 0xc0, 0x57, 0xf4, 0x53, 0x99, 0xae, 0x80, 0x45, 0x88, 0x31, 0xc6,
	0x5b, 0x67, 0xe6, 0xe5, 0xbd, 0x99, 0x5f, 0x17, 0xaa, 0xb3, 0x44, 0xb1, 0x1a, 0xab, 0xc8, 0x37,
	0x1f, 0xde, 0x1c, 0xca, 0x82, 0xf4, 0x4c, 0xc5, 0x9a, 0xf0, 0x0c, 0x20, 0x60, 0xc9, 0xa9, 0xee,
	0xaa, 0x90, 0x5c, 0xab, 0x61, 0xb5, 0x6c, 0x01, 0x7a, 0xdd, 0xc9, 0xe6, 0xdd, 0x54, 0xb3, 0x8a,
	0xcc, 0x7c, 0xaf, 0x61, 0xb5, 0x2a, 0x02, 0xc6, 0xeb, 0x0e, 0xba, 0x50, 0x7a, 0x20, 0xad, 0xe5,
	0x0b, 0xb9, 0xb6, 0x19, 0x96, 0xa2, 0xcf, 0x12, 0x11, 0x9c, 0x9e, 0x64, 0xe9, 0x3a, 0x0d, 0xab,
	0x75, 0x20, 0x9c, 0x50, 0xb2, 0xf4, 0xce, 0x01, 0x6f, 0xe6, 0x4c, 0x49, 0x2c, 0xa7, 0x7d, 0x62,
	0x41, 0xaf, 0x29, 0x69, 0xc6, 0x23, 0xb0, 0xef, 0x68, 0x61, 0xc2, 0x2b, 0xc2, 0x9e, 0xd0, 0xc2,
	0xeb, 0x7c, 0xe9, 0x82, 0x1f, 0x74, 0x78, 0x0c, 0x85, 0xa1, 0x9c, 0xa6, 0xab, 0xc5, 0x0a, 0x6f,
	0x59, 0xe1, 0x09, 0xc0, 0x41, 0xbc, 0x95, 0x52, 0x87, 0xe2, 0xa3, 0x0a, 0x69, 0xd0, 0x5b, 0x1a,
	0x14, 0x63, 0x53, 0x65, 0x7b, 0x3e, 0x51, 0x12, 0x19, 0x0b, 0x5b, 0x38, 0x4c, 0x49, 0x94, 0x25,
	0x4d, 0x68, 0xb1, 0xbc, 0xc8, 0x6c, 0x34, 0x84, 0xfa, 0x3d, 0xc9, 0x90, 0x92, 0x5b, 0x92, 0x09,
	0x8f, 0x48, 0xfe, 0x93, 0x6f, 0x07, 0xaa, 0xd7, 0x7a, 0x32, 0x54, 0x4c, 0x7f, 0xf0, 0x6b, 0x3f,
	0x43, 0x79, 0xc5, 0x09, 0x9b, 0x60, 0xf7, 0x89, 0xb1, 0xe6, 0x6f, 0x13, 0x3e, 0xad, 0xf8, 0xeb,
	0x1f, 0xde, 0x04, 0x3b, 0xd8, 0x90, 0x05, 0xbb, 0x64, 0xed, 0x77, 0x0b, 0xca, 0x2b, 0x88, 0x78,
	0x01, 0xfb, 0x39, 0xa0, 0x58, 0xf3, 0xb7, 0xf1, 0xe6, 0x23, 0x72, 0xf2, 0xe0, 0x17, 0xf2, 0x2b,
	0xa8, 0x05, 0x14, 0x87, 0xdf, 0xf0, 0xe2, 0x89, 0xbf, 0x1b, 0xf8, 0xe6, 0x31, 0xa5, 0x25, 0x3d,
	0x3c, 0xf4, 0x37, 0x39, 0xe6, 0x64, 0xa3, 0xa2, 0x79, 0xf7, 0x97, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xec, 0x5f, 0xec, 0xa3, 0x09, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExternalClient is the client API for External service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExternalClient interface {
	Get(ctx context.Context, in *ExternalGetRequest, opts ...grpc.CallOption) (*Response, error)
	Set(ctx context.Context, in *ExternalSetRequest, opts ...grpc.CallOption) (*Response, error)
}

type externalClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalClient(cc grpc.ClientConnInterface) ExternalClient {
	return &externalClient{cc}
}

func (c *externalClient) Get(ctx context.Context, in *ExternalGetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/External/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalClient) Set(ctx context.Context, in *ExternalSetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/External/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServer is the server API for External service.
type ExternalServer interface {
	Get(context.Context, *ExternalGetRequest) (*Response, error)
	Set(context.Context, *ExternalSetRequest) (*Response, error)
}

// UnimplementedExternalServer can be embedded to have forward compatible implementations.
type UnimplementedExternalServer struct {
}

func (*UnimplementedExternalServer) Get(ctx context.Context, req *ExternalGetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedExternalServer) Set(ctx context.Context, req *ExternalSetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterExternalServer(s *grpc.Server, srv ExternalServer) {
	s.RegisterService(&_External_serviceDesc, srv)
}

func _External_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Get(ctx, req.(*ExternalGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _External_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/External/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServer).Set(ctx, req.(*ExternalSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _External_serviceDesc = grpc.ServiceDesc{
	ServiceName: "External",
	HandlerType: (*ExternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _External_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _External_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocom.proto",
}

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalClient interface {
	InternalGet(ctx context.Context, in *InternalGetRequest, opts ...grpc.CallOption) (*Response, error)
	InternalSet(ctx context.Context, in *InternalGetRequest, opts ...grpc.CallOption) (*Response, error)
	SendLeaderHeartbeat(ctx context.Context, in *LeaderHeartbeatRequest, opts ...grpc.CallOption) (*Response, error)
	AskVote(ctx context.Context, in *AskVoteRequest, opts ...grpc.CallOption) (*Response, error)
}

type internalClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalClient(cc grpc.ClientConnInterface) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) InternalGet(ctx context.Context, in *InternalGetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Internal/InternalGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) InternalSet(ctx context.Context, in *InternalGetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Internal/InternalSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) SendLeaderHeartbeat(ctx context.Context, in *LeaderHeartbeatRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Internal/SendLeaderHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) AskVote(ctx context.Context, in *AskVoteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Internal/AskVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServer is the server API for Internal service.
type InternalServer interface {
	InternalGet(context.Context, *InternalGetRequest) (*Response, error)
	InternalSet(context.Context, *InternalGetRequest) (*Response, error)
	SendLeaderHeartbeat(context.Context, *LeaderHeartbeatRequest) (*Response, error)
	AskVote(context.Context, *AskVoteRequest) (*Response, error)
}

// UnimplementedInternalServer can be embedded to have forward compatible implementations.
type UnimplementedInternalServer struct {
}

func (*UnimplementedInternalServer) InternalGet(ctx context.Context, req *InternalGetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalGet not implemented")
}
func (*UnimplementedInternalServer) InternalSet(ctx context.Context, req *InternalGetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalSet not implemented")
}
func (*UnimplementedInternalServer) SendLeaderHeartbeat(ctx context.Context, req *LeaderHeartbeatRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLeaderHeartbeat not implemented")
}
func (*UnimplementedInternalServer) AskVote(ctx context.Context, req *AskVoteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskVote not implemented")
}

func RegisterInternalServer(s *grpc.Server, srv InternalServer) {
	s.RegisterService(&_Internal_serviceDesc, srv)
}

func _Internal_InternalGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).InternalGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Internal/InternalGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).InternalGet(ctx, req.(*InternalGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_InternalSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).InternalSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Internal/InternalSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).InternalSet(ctx, req.(*InternalGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_SendLeaderHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).SendLeaderHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Internal/SendLeaderHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).SendLeaderHeartbeat(ctx, req.(*LeaderHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_AskVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).AskVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Internal/AskVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).AskVote(ctx, req.(*AskVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Internal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalGet",
			Handler:    _Internal_InternalGet_Handler,
		},
		{
			MethodName: "InternalSet",
			Handler:    _Internal_InternalSet_Handler,
		},
		{
			MethodName: "SendLeaderHeartbeat",
			Handler:    _Internal_SendLeaderHeartbeat_Handler,
		},
		{
			MethodName: "AskVote",
			Handler:    _Internal_AskVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocom.proto",
}
